#Gitlab cicd main 
stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

build-docker-image-prod:
  tags:
    - diffiere

  image: registry.gitlab.com/everst/diffiere/diffie/diffiereplus-backend:docker-aws-cli

  services:
    - docker:dind

  rules: 
    - if: $CI_COMMIT_BRANCH == 'production'

  before_script:
    - aws ecr get-login-password --region us-east-1
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 339439922942.dkr.ecr.us-east-1.amazonaws.com
  

  script:
    - docker build --no-cache . -t 339439922942.dkr.ecr.us-east-1.amazonaws.com/diffiere-plus:$CI_COMMIT_SHA --build-arg PM2_PUBLIC_KEY=$PM2_PUBLIC_KEY --build-arg PM2_SECRET_KEY=$PM2_SECRET_KEY --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID --build-arg ENV_FILE_LOCATION=$ENV_FILE_LOCATION_PROD
    - docker push 339439922942.dkr.ecr.us-east-1.amazonaws.com/diffiere-plus:$CI_COMMIT_SHA
    - docker tag 339439922942.dkr.ecr.us-east-1.amazonaws.com/diffiere-plus:$CI_COMMIT_SHA 339439922942.dkr.ecr.us-east-1.amazonaws.com/diffiere-plus:latest-prod
    - docker push 339439922942.dkr.ecr.us-east-1.amazonaws.com/diffiere-plus:latest-prod


build-docker-image-stage:
  tags:
    - diffiere

  image: registry.gitlab.com/everst/diffiere/diffie/diffiereplus-backend:docker-aws-cli

  services:
    - docker:dind

  rules: 
    - if: $CI_COMMIT_BRANCH == 'main'

  before_script:
    - aws ecr get-login-password --region us-east-1
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 339439922942.dkr.ecr.us-east-1.amazonaws.com
  

  script:
    - docker build --no-cache . -t 339439922942.dkr.ecr.us-east-1.amazonaws.com/diffiere-plus:$CI_COMMIT_SHA --build-arg PM2_PUBLIC_KEY=$PM2_PUBLIC_KEY --build-arg PM2_SECRET_KEY=$PM2_SECRET_KEY --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID --build-arg ENV_FILE_LOCATION=$ENV_FILE_LOCATION_STAGE
    - docker push 339439922942.dkr.ecr.us-east-1.amazonaws.com/diffiere-plus:$CI_COMMIT_SHA
    - docker tag 339439922942.dkr.ecr.us-east-1.amazonaws.com/diffiere-plus:$CI_COMMIT_SHA 339439922942.dkr.ecr.us-east-1.amazonaws.com/diffiere-plus:latest-stage
    - docker push 339439922942.dkr.ecr.us-east-1.amazonaws.com/diffiere-plus:latest-stage


build-docker-image-dev:
  tags:
    - diffiere

  image: registry.gitlab.com/everst/diffiere/diffie/diffiereplus-backend:docker-aws-cli

  services:
    - docker:dind

  rules:
    - if: $CI_COMMIT_BRANCH == 'development'

  before_script:
    - aws ecr get-login-password --region us-east-1
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 339439922942.dkr.ecr.us-east-1.amazonaws.com

  script:
    - docker build --no-cache . -t 339439922942.dkr.ecr.us-east-1.amazonaws.com/diffiere-plus:$CI_COMMIT_SHA --build-arg PM2_PUBLIC_KEY=$PM2_PUBLIC_KEY --build-arg PM2_SECRET_KEY=$PM2_SECRET_KEY --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID --build-arg ENV_FILE_LOCATION=$ENV_FILE_LOCATION_DEV
    - docker push 339439922942.dkr.ecr.us-east-1.amazonaws.com/diffiere-plus:$CI_COMMIT_SHA
    - docker tag 339439922942.dkr.ecr.us-east-1.amazonaws.com/diffiere-plus:$CI_COMMIT_SHA 339439922942.dkr.ecr.us-east-1.amazonaws.com/diffiere-plus:latest-dev
    - docker push 339439922942.dkr.ecr.us-east-1.amazonaws.com/diffiere-plus:latest-dev
  
test-and-lint:
  tags:
    - diffiere
  
  image: node:lts-alpine3.14

  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

  script:
    - npm install
    - npm run lint:ci
    - npm run test

